services:
  postgres:
    image: postgres:15-alpine
    container_name: general-contractor-quotes-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: general-contractor-quotes-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "5555:5555"  # Prisma Studio port
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    networks:
      - app-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge